name: LatchEssentials
version: 1.2
main: lmp.Main
api-version: 1.19
depend: [ ProtocolLib, Vault ]
commands:
  bp:
    description: "BackPack"
  ps:
    description: "Player Shop"
  am:
    description: "Auto Miner"
  lmp:
    description: "LMP Server Command"
  dtsc:
    description: "Discord Staff Chat"
  twitch:
    description: "Twitch Bot"
  adsc:
    description: "Admin Staff Chat"
  dcmsg:
    description: "Message Discord User from the Server"
  hardcore:
    description: "Hardcore Command"
  anarchy:
    description: "Anarchy Command"